# Generated by Django 3.0.2 on 2020-01-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='user',
        ),
    ]
