# Generated by Django 3.0.2 on 2020-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0003_residente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosResidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residente', models.CharField(max_length=50)),
                ('escuela', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
