# Generated by Django 3.0.2 on 2020-02-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0006_remove_datosresidente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosresidente',
            name='fecha',
            field=models.CharField(max_length=25),
        ),
    ]
