# Generated by Django 3.0.2 on 2020-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_proyectos', '0007_auto_20200212_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.ImageField(upload_to='archivos')),
            ],
        ),
    ]
