# Generated by Django 3.0.2 on 2020-02-14 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_proyectos', '0009_auto_20200214_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='upload',
            new_name='pdf',
        ),
        migrations.RemoveField(
            model_name='media',
            name='save',
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
