# Generated by Django 3.0.2 on 2020-02-26 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_proyectos', '0011_datosresidente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('area', models.CharField(max_length=80)),
                ('disponible', models.CharField(max_length=80)),
                ('cantidad', models.CharField(max_length=80)),
                ('proyecto', models.ImageField(upload_to='proyectos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
