# Generated by Django 3.0.2 on 2020-02-26 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_proyectos', '0012_datosadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosAdmin',
            new_name='Administradores',
        ),
    ]
