# Generated by Django 3.0.2 on 2020-02-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banco_proyectos', '0014_remove_administradores_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_residentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento', models.ImageField(upload_to='Actas_Nacimiento/')),
                ('curp', models.ImageField(upload_to='Curp/')),
                ('Ine', models.ImageField(upload_to='Ine/Ife/')),
                ('domicilio', models.ImageField(upload_to='Comporbante_Domicilio/')),
                ('comprobante_estudio', models.ImageField(upload_to='Comprobante_Estudios/')),
                ('carta_presentación', models.ImageField(upload_to='Carta_Presentación/')),
                ('certificado_medico', models.ImageField(upload_to='Certificado_Medico/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
